version: 2
machine:
  timezone: America/Los_Angeles # Set the timezone
  node:
    version: 7.10
  environment:
    CIRCLE_ENV: test
jobs:
  checkout-job:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/DW_Bot
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  ui-test-job:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/DW_Bot
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint
  integration-test-job:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/DW_Bot
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint
  unit-test-job:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/DW_Bot
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint
  lint-test-job:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/DW_Bot
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint
  fake-deploy-job:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/DW_Bot
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0,30 * * * *"
          filters:
            branches:
              only:
                - master
                - circle
    jobs:
      - checkout-job
      - integration-test-job:
          requires:
            - checkout-job
  test-all-workflow:
    jobs:
      - checkout-job
      - unit-test-job:
          requires:
            - checkout-job
      - integration-test-job:
          requires:
            - checkout-job
      - lint-test-job:
          requires:
            - checkout-job
      - fake-deploy-job:
          requires:
            - unit-test-job
            - integration-test-job
            - lint-test-job
